name: inside
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+1
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.0.2
  dots_indicator: ^1.0.0
  align_positioned: any
  image_picker: ^0.6.1+8
  image_cropper: ^1.1.0
  super_tooltip: ^0.9.0
  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  equatable: ^0.6.1
  flutter_bloc: ^0.22.1
  flip_card: ^0.4.3
  path: ^1.6.4
  location: ^2.3.5
  geoflutterfire: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_tindercard: ^0.1.8
  mime_type: ^0.2.4
  intl: ^0.15.8
  flushbar: ^1.9.1
  network_to_file_image: ^2.0.7
  path_provider: ^0.4.1
  bubble: ^1.1.9+1
  cloud_functions: ^0.4.1+1
  uuid: ^2.0.2
  simple_animations: ^1.3.3
  keyboard_visibility: ^0.5.6
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
      sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
